# Generated by Django 2.2.9 on 2020-04-24 15:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WakeCorporate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('short_name', models.CharField(max_length=3)),
                ('long_name', models.CharField(max_length=13)),
                ('ordinance_field', models.CharField(max_length=18)),
                ('effective_field', models.CharField(max_length=24)),
                ('shapearea', models.FloatField()),
                ('shapelen', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
